sudo: required
dist: xenial
language: node_js
node_js:
  - stable
cache: npm

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - guozetang@gmail.com # 设置通知邮件
    on_success: change
    on_failure: always

install:
  - npm install gitbook-cli -g
  - gitbook install

script:
  - chmod +x ./scripts/hexotogitbook.sh
  - ./scripts/hexotogitbook.sh
  - mv ./leetcode/* .
  - gitbook build

after_script:
  - chmod +x ./scripts/build.sh
  - ./scripts/build.sh

env:
  global:
    - REF=github.com/guozetang/leetcode.git
