sudo: required
dist: xenial
language: node_js
node_js:
  - stable
cache: npm

branches:
  only:
    - master
    - dev

notifications:
  email:
    recipients:
      - guozetang@gmail.com # 设置通知邮件
    on_success: change
    on_failure: always

install:
  - sudo apt-get install calibre
  - npm install gitbook-cli -g

script:
  - cd leetcode
  - make init
  - make all

after_script:
  - make push

env:
  global:
    - REF=github.com/guozetang/leetcode.git
